name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: befor build
      run: rustup target add aarch64-linux-android x86_64-linux-android
    - name: build
      run: bash ./app/src/main/rust/leaf-android/build.sh debug
